# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-20 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('openHour', models.TimeField()),
                ('closeHour', models.TimeField()),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('tickets', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'dbi04web_events',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantityMembers', models.IntegerField(max_length=11)),
                ('url', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField()),
            ],
            options={
                'db_table': 'dbi02web_groups',
            },
        ),
        migrations.CreateModel(
            name='GroupTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'dbi01web_group_types',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=255)),
                ('skills', models.TextField()),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_integration.Group')),
            ],
            options={
                'db_table': 'dbi03web_members',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_integration.GroupTypes'),
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_integration.Group'),
        ),
    ]
